### ISSUE TITLE
D2RQ error with d2rq-0.8-maven

### ISSUE THREAD

**Issue by boferri** [LinkedBrainz/LinkedBrainzTestcases#2]
Some tests of the Medium, Release and Work test suites are causing a NullPointerException in D2RQ (d2rq-0.8-maven [1]), see

```
INFO  SPARQL               :: Throwable: null
java.lang.NullPointerException
    at de.fuberlin.wiwiss.d2rq.optimizer.utility.OpFilterUtility.applyDistributivLaw(OpFilterUtility.java:91)
    at de.fuberlin.wiwiss.d2rq.optimizer.utility.OpFilterUtility.translateFilterExpressionsToCNF(OpFilterUtility.java:46)
    at de.fuberlin.wiwiss.d2rq.optimizer.transformer.TransformPrepareOpTreeForOptimizing.transform(TransformPrepareOpTreeForOptimizing.java:87)
    at com.hp.hpl.jena.sparql.algebra.op.OpFilter.apply(OpFilter.java:94)
    at com.hp.hpl.jena.sparql.algebra.Transformer$ApplyTransformVisitor.visit1(Transformer.java:270)
    at com.hp.hpl.jena.sparql.algebra.Transformer$ApplyTransformVisitor.visit(Transformer.java:154)
    at com.hp.hpl.jena.sparql.algebra.op.OpFilter.visit(OpFilter.java:96)
    at com.hp.hpl.jena.sparql.algebra.OpWalker$WalkerVisitor.visit1(OpWalker.java:85)
    at com.hp.hpl.jena.sparql.algebra.OpVisitorByType.visit(OpVisitorByType.java:71)
    at com.hp.hpl.jena.sparql.algebra.op.OpFilter.visit(OpFilter.java:96)
    at com.hp.hpl.jena.sparql.algebra.OpWalker$WalkerVisitor.visit1(OpWalker.java:84)
    at com.hp.hpl.jena.sparql.algebra.OpVisitorByType.visitModifer(OpVisitorByType.java:26)
    at com.hp.hpl.jena.sparql.algebra.OpVisitorByType.visit(OpVisitorByType.java:107)
    at com.hp.hpl.jena.sparql.algebra.op.OpProject.visit(OpProject.java:34)
    at com.hp.hpl.jena.sparql.algebra.OpWalker$WalkerVisitor.visit1(OpWalker.java:84)
    at com.hp.hpl.jena.sparql.algebra.OpVisitorByType.visitModifer(OpVisitorByType.java:26)
    at com.hp.hpl.jena.sparql.algebra.OpVisitorByType.visit(OpVisitorByType.java:113)
    at com.hp.hpl.jena.sparql.algebra.op.OpDistinct.visit(OpDistinct.java:34)
    at com.hp.hpl.jena.sparql.algebra.OpWalker.walk(OpWalker.java:40)
    at com.hp.hpl.jena.sparql.algebra.OpWalker.walk(OpWalker.java:30)
    at com.hp.hpl.jena.sparql.algebra.Transformer.applyTransformation(Transformer.java:99)
    at com.hp.hpl.jena.sparql.algebra.Transformer.transformation(Transformer.java:92)
    at com.hp.hpl.jena.sparql.algebra.Transformer.transformation(Transformer.java:81)
    at com.hp.hpl.jena.sparql.algebra.Transformer.transform(Transformer.java:42)
    at de.fuberlin.wiwiss.d2rq.optimizer.D2RQTreeOptimizer.optimize(D2RQTreeOptimizer.java:96)
    at de.fuberlin.wiwiss.d2rq.engine.QueryEngineD2RQ.modifyOp(QueryEngineD2RQ.java:50)
    at com.hp.hpl.jena.sparql.engine.QueryEngineBase.createPlan(QueryEngineBase.java:104)
    at com.hp.hpl.jena.sparql.engine.QueryEngineBase.getPlan(QueryEngineBase.java:97)
    at de.fuberlin.wiwiss.d2rq.engine.QueryEngineD2RQ$QueryEngineFactoryD2RQ.create(QueryEngineD2RQ.java:81)
    at com.hp.hpl.jena.sparql.engine.QueryExecutionBase.getPlan(QueryExecutionBase.java:426)
    at com.hp.hpl.jena.sparql.engine.QueryExecutionBase.startQueryIterator(QueryExecutionBase.java:400)
    at com.hp.hpl.jena.sparql.engine.QueryExecutionBase.execResultSet(QueryExecutionBase.java:408)
    at com.hp.hpl.jena.sparql.engine.QueryExecutionBase.execSelect(QueryExecutionBase.java:135)
    at org.joseki.processors.SPARQL.executeQuery(SPARQL.java:317)
    at org.joseki.processors.SPARQL.execQueryWorker(SPARQL.java:296)
    at org.joseki.processors.SPARQL.execQueryProtected(SPARQL.java:126)
    at org.joseki.processors.SPARQL.execQuery(SPARQL.java:120)
    at org.joseki.processors.QueryCom.execOperation(QueryCom.java:19)
    at org.joseki.processors.ProcessorBase.exec(ProcessorBase.java:76)
    at org.joseki.Service.exec(Service.java:28)
    at org.joseki.Dispatcher.dispatch(Dispatcher.java:50)
    at org.joseki.http.Servlet.doCommon(Servlet.java:172)
    at org.joseki.http.Servlet.doGet(Servlet.java:133)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:487)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:362)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:181)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:726)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:405)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:324)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:505)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:829)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:514)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:211)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:380)
    at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:488)
```

At a first glance these tests make use of SPARQL FILTER expressions.

[1] https://github.com/zazi/D2RS-LinkedBrainz/tree/d2rs-0.8-maven

**Comment by boferri** [comment]
See also the output of the related test suites:

[1] https://github.com/LinkedBrainz/LinkedBrainzTestcases/blob/0.0.2/testoutput/MediumTest_-_results
[2] https://github.com/LinkedBrainz/LinkedBrainzTestcases/blob/0.0.2/testoutput/ReleaseTest_-_results
[3] https://github.com/LinkedBrainz/LinkedBrainzTestcases/blob/0.0.2/testoutput/WorkTest_-_results
